/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkkp;

/**
 *
 * @author joni
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mndata = new javax.swing.JMenu();
        mnPeserta = new javax.swing.JMenuItem();
        mnUser = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnKota = new javax.swing.JMenuItem();
        mnKec = new javax.swing.JMenuItem();
        mnKel = new javax.swing.JMenuItem();
        mnJual = new javax.swing.JMenu();
        mnSeleksi = new javax.swing.JMenuItem();
        mnNilai = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnLapPeserta = new javax.swing.JMenuItem();
        mnLolosSeleksi = new javax.swing.JMenuItem();
        mnLapNilai = new javax.swing.JMenuItem();
        mnLapPesLolos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnBkp = new javax.swing.JMenuItem();
        mnKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aplikasi FKKP UAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 36)); // NOI18N
        jLabel2.setText("FKKP JATENG");

        mndata.setText("Data Master");

        mnPeserta.setText("Data Peserta");
        mnPeserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPesertaActionPerformed(evt);
            }
        });
        mndata.add(mnPeserta);

        mnUser.setText("Kelola User");
        mnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUserActionPerformed(evt);
            }
        });
        mndata.add(mnUser);
        mndata.add(jSeparator1);

        mnKota.setText("Data Kota/Kab");
        mnKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKotaActionPerformed(evt);
            }
        });
        mndata.add(mnKota);

        mnKec.setText("Data Kecamatan");
        mnKec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKecActionPerformed(evt);
            }
        });
        mndata.add(mnKec);

        mnKel.setText("Data Kelurahan");
        mnKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKelActionPerformed(evt);
            }
        });
        mndata.add(mnKel);

        jMenuBar1.add(mndata);

        mnJual.setText("Transaksi");

        mnSeleksi.setText("Seleksi Administrasi");
        mnSeleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSeleksiActionPerformed(evt);
            }
        });
        mnJual.add(mnSeleksi);

        mnNilai.setText("Penilaian Peserta");
        mnNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNilaiActionPerformed(evt);
            }
        });
        mnJual.add(mnNilai);

        jMenuBar1.add(mnJual);

        jMenu3.setText("Laporan");

        mnLapPeserta.setText("Laporan Peserta");
        mnLapPeserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapPesertaActionPerformed(evt);
            }
        });
        jMenu3.add(mnLapPeserta);

        mnLolosSeleksi.setText("Lolos Seleksi Administrasi");
        mnLolosSeleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLolosSeleksiActionPerformed(evt);
            }
        });
        jMenu3.add(mnLolosSeleksi);

        mnLapNilai.setText("Laporan Nilai");
        mnLapNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapNilaiActionPerformed(evt);
            }
        });
        jMenu3.add(mnLapNilai);

        mnLapPesLolos.setText("Laporan Peserta Lolos");
        mnLapPesLolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapPesLolosActionPerformed(evt);
            }
        });
        jMenu3.add(mnLapPesLolos);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Utility");

        mnBkp.setText("Backup Data");
        mnBkp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBkpActionPerformed(evt);
            }
        });
        jMenu4.add(mnBkp);

        mnKeluar.setText("Keluar");
        mnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKeluarActionPerformed(evt);
            }
        });
        jMenu4.add(mnKeluar);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUserActionPerformed
        new dataUser().setVisible(true);
    }//GEN-LAST:event_mnUserActionPerformed

    private void mnPesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPesertaActionPerformed
        new dataPeserta().setVisible(true);
    }//GEN-LAST:event_mnPesertaActionPerformed

    private void mnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnKeluarActionPerformed

    private void mnKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKotaActionPerformed
        new datakota().setVisible(true);
    }//GEN-LAST:event_mnKotaActionPerformed

    private void mnKecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKecActionPerformed
        new dataKecamatan().setVisible(true);
    }//GEN-LAST:event_mnKecActionPerformed

    private void mnKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKelActionPerformed
        new dataKelurahan().setVisible(true);
    }//GEN-LAST:event_mnKelActionPerformed

    private void mnBkpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBkpActionPerformed
        new frmBackup().setVisible(true);
    }//GEN-LAST:event_mnBkpActionPerformed

    private void mnSeleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSeleksiActionPerformed
        new transSeleksi().setVisible(true);
    }//GEN-LAST:event_mnSeleksiActionPerformed

    private void mnNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNilaiActionPerformed
        new transNilai().setVisible(true);
    }//GEN-LAST:event_mnNilaiActionPerformed

    private void mnLapPesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapPesertaActionPerformed
        new lapPeserta().setVisible(true);
    }//GEN-LAST:event_mnLapPesertaActionPerformed

    private void mnLolosSeleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLolosSeleksiActionPerformed
        new lapSeleksi().setVisible(true);
    }//GEN-LAST:event_mnLolosSeleksiActionPerformed

    private void mnLapNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapNilaiActionPerformed
        new lapNilai().setVisible(true);
    }//GEN-LAST:event_mnLapNilaiActionPerformed

    private void mnLapPesLolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapPesLolosActionPerformed
        new lapPesertaLolos().setVisible(true);
    }//GEN-LAST:event_mnLapPesLolosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnBkp;
    private javax.swing.JMenu mnJual;
    private javax.swing.JMenuItem mnKec;
    private javax.swing.JMenuItem mnKel;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenuItem mnKota;
    private javax.swing.JMenuItem mnLapNilai;
    private javax.swing.JMenuItem mnLapPesLolos;
    private javax.swing.JMenuItem mnLapPeserta;
    private javax.swing.JMenuItem mnLolosSeleksi;
    private javax.swing.JMenuItem mnNilai;
    private javax.swing.JMenuItem mnPeserta;
    private javax.swing.JMenuItem mnSeleksi;
    private javax.swing.JMenuItem mnUser;
    private javax.swing.JMenu mndata;
    // End of variables declaration//GEN-END:variables
}
